kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:latest
  environment:
    D_USERNAME:
      from_secret: D_USERNAME
    D_PASSWPRD:
      from_secret: D_PASSWPRD 
  commands:
  - ./build.sh
  when:
    branch:
    - master

trigger:
  event:
    - push

