kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: docker:latest
    environment:
      D_USERNAME:
        from_secret: D_USERNAME
      D_PASSWORD:
        from_secret: D_PASSWORD
    commands:
      - ./build.sh
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    when:
      branch:
        - master

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
    - custom
    - cron

