kind: pipeline
type: docker
name: build

steps:
- name: build
  image: docker:latest
  environment:
    D_USERNAME:
      from_secret: D_USERNAME
    D_PASSWORD:
      from_secret: D_PASSWORD
  commands:
  - ./build.sh
  when:
    branch:
    - master

trigger:
  event:
    - push

