kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:latest
  commands:
  - pwd
  - ls -lah
  - bash build.sh
  when:
    branch:
    - master

trigger:
  event:
    - push

