version: 2.1

jobs:
  build:
    machine:
        image: ubuntu-2004:202010-01
        docker_layer_caching: false

    steps:
      - checkout

      - run:
          name: Build images
          command: ./build.sh


workflows:
  version: 2
  build:
    jobs:
      - build
  monthly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: 0 5 1 * * # Build once a month
          filters:
            branches:
              only:
              - master
